// Code generated by goctl. DO NOT EDIT.
package types

type OutputReq struct {
	QuestionType     int `form:"questionType"`
	FirmID           string `form:"firmID"`
	CurrentTimestamp string `form:"currentTimestamp"`
	DigitalSignature string `form:"digitalSignature"`
}

type OutputReply struct {
	Question      string `json:"question"`
	Answer        string `json:"answer"`
	DisturbAnswer string    `json:"disturbAnswer"`
}
