// Code generated by goctl. DO NOT EDIT.
package handler

import (

	"net/http"

	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method: http.MethodOptions,
				Path: "/login/question",
				Handler: func(w http.ResponseWriter, r *http.Request) {
				},
			},
			{
				Method: http.MethodOptions,
				Path: "/login/isAnswer",
				Handler: func(w http.ResponseWriter, r *http.Request) {},
			},
			{
				Method: http.MethodOptions,
				Path: "/login/sendMsg",
				Handler: func(w http.ResponseWriter, r *http.Request) {},
			},
			{
				Method: http.MethodOptions,
				Path: "/login/employee",
				Handler: func(w http.ResponseWriter, r *http.Request) {},
			},
			{
				Method:  http.MethodGet,
				Path:    "/login/question",
				Handler: getQuestionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/login/isAnswer",
				Handler: isAnswerHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/login/sendMsg",
				Handler: SendMsgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login/employee",
				Handler: EmployeeHandler(serverCtx),
			},
		},
	)
}
