// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: pongHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/edit/item",
				Handler: ItemHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/edit/userInfo",
				Handler: UserInfoHandler(serverCtx),
			},
		},
	)
}
