// Code generated by goctl. DO NOT EDIT!
// Source: login.proto

package server

import (
	"context"

	"rpc/internal/logic"
	"rpc/internal/svc"
	"rpc/types/login"
)

type LoginServer struct {
	svcCtx *svc.ServiceContext
	login.UnimplementedLoginServer
}

func NewLoginServer(svcCtx *svc.ServiceContext) *LoginServer {
	return &LoginServer{
		svcCtx: svcCtx,
	}
}

func (s *LoginServer) SendMsg(ctx context.Context, in *login.SendMsgRequest) (*login.SendMsgResponse, error) {
	l := logic.NewSendMsgLogic(ctx, s.svcCtx)
	return l.SendMsg(in)
}

func (s *LoginServer) AddEmployee(ctx context.Context, in *login.EmployeeRequest) (*login.EmployeeResponse, error) {
	l := logic.NewAddEmployeeLogic(ctx, s.svcCtx)
	return l.AddEmployee(in)
}
