// Code generated by goctl. DO NOT EDIT.
package types

type QuestionReq struct {
}

type QuestionReply struct {
	Question     string `json:"question"`
	RandomAnswer string `json:"randomAnswer"`
	Token        string `json:"token"`
}

type IsAnswerReq struct {
	Answer   string `form:"answer"`
	Token    string `header:"authorization"`
}

type IsAnswerReply struct {
	Result bool `json:"result"`
}

type SendMsgReq struct {
	MobileNum string `form:"mobileNum"`
	Token     string `header:"authorization"`
}

type SendMsgReply struct {
}

type EmployeeReq struct {
	MobileNum string `json:"mobileNum"`
	MsgCode   string `json:"msgCode"`
	Token     string `header:"authorization"`
}

type EmployeeReply struct {
	Token string `json:"token,optional"`
}
