// Code generated by goctl. DO NOT EDIT.
package types

type ItemReq struct {
	QuestionType  string `json:"questionType"`
	Question      string `json:"question"`
	Answer        string `json:"answer"`
	DisturbAnswer string `json:"disturbAnswer"`
	MobileNum     string `json:"mobileNum"`
}

type ItemReply struct {
}

type UserInfoReq struct {
	MobileNum string `form:"mobileNum"`
}

type UserInfoReply struct {
	EmployeeLevel     int    `json:"employeeLevel"`
	ContributionScore int    `json:"contributionScore"`
	AuditScore        int    `json:"auditScore"`
	RegistrationTime  string `json:"registrationTime"`
}
