// Code generated by goctl. DO NOT EDIT!
// Source: output.proto

package server

import (
	"context"

	"rpc/internal/logic"
	"rpc/internal/svc"
	"rpc/types/output"
)

type OutputServer struct {
	svcCtx *svc.ServiceContext
	output.UnimplementedOutputServer
}

func NewOutputServer(svcCtx *svc.ServiceContext) *OutputServer {
	return &OutputServer{
		svcCtx: svcCtx,
	}
}

func (s *OutputServer) GetItem(ctx context.Context, in *output.OutputRequest) (*output.OutputResponse, error) {
	l := logic.NewGetItemLogic(ctx, s.svcCtx)
	return l.GetItem(in)
}
